Repository janik6882/CGoL, pull requests merged in 2021-02, with the labels that each got.

#8 Saving advances
  .gitignore
  backend.py
Labels: enhancement

#18 GUI
  GUI.py
Labels: new feature

#22 Frontend typing
  .gitignore
  backend.py
  frontend.py
Labels: documentation, enhancement
