Repository janik6882/CGoL, pull requests merged in 2021-03, with the labels that each got.

#39 bugfixes an datei laden gemacht
  frontend.py
Labels: bug, bugfix, enhancement

#41 Janik6882 mouse trail integration
  frontend.py
Labels: aktuelle Arbeit, documentation, new feature, optimierung

#43 Das Seitenmenü und die Counter sind implementiert
  backend.py
  frontend.py
Labels: aktuelle Arbeit, enhancement, new feature

#45 Janik6882 sidebar bugfixes
  frontend.py
Labels: aktuelle Arbeit, bug, bugfix, enhancement

#46 Fix für previous_premade()
  frontend.py
Labels: aktuelle Arbeit, bug, bugfix

#64 Janik682 board zentrieren
  frontend.py
Labels: enhancement, new feature

#70 Janik6882 wasd steuerung
  frontend.py
Labels: bugfix, enhancement, new feature

#71 Janik6882 dokumentation update
  frontend.py
Labels: documentation, enhancement

#72 kleinere Änderungen
  premade/premade.json
Labels: bug, bugfix, enhancement

#79 drehen von Premade objekten ermöglicht
  lib/DisplayClass.py
  lib/backend.py
Labels: aktuelle Arbeit, enhancement, new feature

#81 bugfixes und import premade button mit funktionalität hinzugefügt
  lib/DisplayClass.py
Labels: aktuelle Arbeit, enhancement, new feature

#82 Bedienungsanleitung hinzugefügt
  Projekt_Bedinungsanleitung.MD
  lib/DisplayClass.py
  lib/Projekt_Bedienungsanleitung.py
Labels: aktuelle Arbeit, enhancement, new feature

#83 bugfixes und enhancements
  lib/DisplayClass.py
Labels: aktuelle Arbeit, bugfix, enhancement

#80 Usermade formen funktioniert
  .project
  lib/DisplayClass.py
  lib/usermadeformen.py
  premade/premade.json
Labels: aktuelle Arbeit, enhancement, new feature

#84 bugfix bei als Form speichern
  lib/DisplayClass.py
  lib/backend.py
Labels: bugfix, enhancement, new feature
